FROM centos:7
LABEL author="steven"
RUN yum groupinstall -y "Development tools"
RUN yum -y install tar gcc zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel
RUN cd /tmp && curl https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz -o Python-2.7.18.tgz \
    && tar zxf Python-2.7.18.tgz && cd Python-2.7.18 && ./configure --enable-optimizations && make altinstall
RUN mv /usr/bin/python2.7 /usr/bin/python2.7.5 && ln -s /usr/local/bin/python2.7 /usr/bin/python2.7
RUN python -V
RUN set -ex \
    && sed -i "s#/usr/bin/python#/usr/bin/python2.7.5#" /usr/bin/yum \
    && sed -i "s#/usr/bin/python#/usr/bin/python2.7.5#" /usr/libexec/urlgrabber-ext-down
RUN cd /tmp && curl https://bootstrap.pypa.io/2.7/get-pip.py -o get-pip.py && python get-pip.py
RUN yum clean all && rm -rf /tmp/*
RUN pip list
