FROM centos:7
LABEL author="steven"
RUN yum update -y && yum install -y gcc openssl-devel bzip2-devel libffi-devel make
RUN cd /tmp && curl -O https://www.python.org/ftp/python/3.8.7/Python-3.8.7.tgz -o Python-3.8.7.tgz \
    && tar -zxf Python-3.8.7.tgz && cd Python-3.8.7 && ./configure --enable-optimizations && make altinstall
RUN yum clean all && rm -rf /tmp/*
RUN python3.8 -V && python3.8 -m pip list
